### ISSUE TITLE
Ability to change the bounds for the regression

### ISSUE THREAD

**Issue by IreneGalca** [cs481-ekh/s21-team-ion#14]
As a user,
I want to be able to set the minimum and/or maximum boundaries of the regression line, either by holding the mouse down in the graph, or by setting them in a textbox,
So that the open probability can be changed in real time.

**Acceptance Criteria**
- [x] The user can drag either the min or max boundary lines in the graph with their mouse  (#13)
- [x] When the boundary lines are dragged by the user, the linear regression will update (#15)
- [x] There are two input boxes that accept floats, one for the minimum boundary line, and one of the maximum boundary line (#19)
- [x] There is an update button near the input boxes. (#20)
- [x] When the values in the input boxes are changed manually (not click-and-drag), and the user presses this update button, the boundary lines are updated (#21)
- [x] When the boundary lines are updated via the update button, the regression line is also updated. (#22)
- [x] When the boundary lines are updated via click-and-drag, the values inside the input boxes should also be updated (#23)
