### ISSUE TITLE
Open probability graph

### ISSUE THREAD

**Issue by vorcepa** [cs481-ekh/s21-team-ion#24]
As a user, I can modify the raw data graph by importing a new file, or by changing the regression boundary lines.
I want to be able to see the open probability graph update when the raw data graph is updated,
So that I can quickly glean information from the data.

**Acceptance Criteria**
- [x] Calculate the open probability (#28)
- [x] The value at 0 volts does not cause a division by zero error (#35)
- [x] Plot the open probability graph to the right of the raw data graph (#30)
