### ISSUE TITLE
Cleanup and optimization

### ISSUE THREAD

**Issue by vorcepa** [cs481-ekh/s21-team-ion#33]
Things to be done to increase the speed of execution, and to make the application appear more professional.

# Acceptance Criteria
- [x] Remove the default matplotlib toolbar (#34)
- [x] Set the lines to be a consistent color (#37)
- [x] Each graph has a title centered above them (#38)
- [x] Fix the mouse cursor not changing when it should be (#40)
- [x] Fix the regression line to update at the appropriate times (#41)
- [x] Limit precision of entry boxes (#42)
- [ ] **Low priority** Increase responsiveness of click-and-drag (#36)
